---
- name: Make sure the {{ container_name }} container is created and running.
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/hotio/prowlarr"
    pull: yes
    state: "started"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "UMASK": "002"
      "TZ": "{{ timezone }}"
      "DOCKER_MODS": "{{ theme_park_repo }}:{{ container_name }}"
      "TP_THEME": '{{ colorscheme | default("") }}'
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
    ports:
      - 9696:9696
    restart_policy: unless-stopped
